spring:
    profiles:
        active:
            - dev
---
server:
    port: 8101

spring:
    profiles: dev
    application:
        name: microconfig-test-client5

eureka:
    client:
        serviceUrl:
            defaultZone: http://admin:enjoy@localhost:7301/eureka
        register-with-eureka: false

info:
    app.name: microcloud-config-bus-client-zkh
    company.name: zkh
---
server:
    port: 8102

spring:
    profiles: beta
    application:
        name: microconfig-test-client5

eureka:
    client:
        serviceUrl:
            defaultZone: http://admin:enjoy@localhost:7301/eureka
        register-with-eureka: false

info:
    app.name: microcloud-config-bus-client-beta2
    company.name: enjoy